name: 2gowaApp

services:
  whatsapp:
    image: aldinokemal2104/go-whatsapp-web-multidevice
    container_name: 2gowaApp
    restart: always

    ports:
      - "3002:3000"

    volumes:
      - 2gowaApp:/app/storages

    command:
      - rest
      - --basic-auth=admin:admin
      - --port=3000
      - --debug=true
      - --os=Chrome
      - --account-validation=false

volumes:
  2gowaApp:
