services:
  n8n:
    image: n8nio/n8n:latest
    container_name: 1n8nApp
    restart: unless-stopped

    ports:
      - "${N8N_PORT}:5678"

    env_file:
      - .env

    volumes:
      - ./data:/home/node/.n8n

    networks:
      - 1n8nApp_net

networks:
  1n8nApp_net:
    name: 1n8nApp
    driver: bridge
