name: wuzapi-stack

services:
  wuzapi:
    image: asternic/wuzapi
    container_name: 1wuzapiApp
    restart: unless-stopped

    ports:
      - "8080:8080"

    environment:
      TZ: Asia/Jakarta
      WUZAPI_ADMIN_TOKEN: alwanadmin

      DB_HOST: wuzapi-postgres
      DB_PORT: 5432
      DB_NAME: wuzapi
      DB_USER: wuzapi
      DB_PASSWORD: wuzapi123

      # üîê HARUS 32 KARAKTER
      WUZAPI_GLOBAL_ENCRYPTION_KEY: 12345678901234567890123456789012
      WUZAPI_GLOBAL_HMAC_KEY: abcdefghijklmnopqrstuvwxyz123456

    volumes:
      - wuzapi_data:/app/dbdata

    networks:
      - pg_net

volumes:
  wuzapi_data:

networks:
  pg_net:
    external: true
    name: wuzapi-stack_default
