services:
  whatsapp:
    image: aldinokemal2104/go-whatsapp-web-multidevice
    container_name: 1gowaApp
    restart: always
    ports:
      - "3002:3000"
    volumes:
      - 1gowaApp:/app/storages
    command:
      - rest
      - --basic-auth=admin:admin
      - --port=3000
      - --debug=true
      - --os=Chrome
      - --account-validation=false
      - --webhook="https://n8n.personal.vaultsy.online/webhook-test/3715ff08-74a9-4402-8b1a-f8c7a9239061"

volumes:
  1gowaApp:
